# ===============================
# DATABASE
# ===============================

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/lab
spring.datasource.username=root
spring.datasource.password=123456a-

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

server.port=8091
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.messages.basename=messages/messages
spring.messages.always-use-message-format=false
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true

rootPath=D:/LAB/LAB4/r7-tech/public/img/
# ===============================
# token info
# ===============================
token.expiration_time=864000000
token.secret_key=f87124ca-8460-11ed-a1eb-0242ac120002
token.token_prefix=r7-tect
token.header_string=Authorization
